// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAuthSessionGraceReuse = `-- name: ClaimAuthSessionGraceReuse :execrows
UPDATE auth_sessions
SET grace_reuse_count = grace_reuse_count + 1
WHERE id = $1::text::uuid
  AND consumed_at IS NOT NULL
  AND grace_expires_at >= $2
  AND grace_reuse_count = 0
  AND revoked_at IS NULL
`

type ClaimAuthSessionGraceReuseParams struct {
	ID  string
	Now pgtype.Timestamptz
}

func (q *Queries) ClaimAuthSessionGraceReuse(ctx context.Context, arg ClaimAuthSessionGraceReuseParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimAuthSessionGraceReuse, arg.ID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeAuthSession = `-- name: ConsumeAuthSession :execrows
UPDATE auth_sessions
SET
    consumed_at = $1,
    grace_expires_at = $2
WHERE id = $3::text::uuid
  AND consumed_at IS NULL
  AND revoked_at IS NULL
`

type ConsumeAuthSessionParams struct {
	ConsumedAt     pgtype.Timestamptz
	GraceExpiresAt pgtype.Timestamptz
	ID             string
}

func (q *Queries) ConsumeAuthSession(ctx context.Context, arg ConsumeAuthSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeAuthSession, arg.ConsumedAt, arg.GraceExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAuthSession = `-- name: CreateAuthSession :one
WITH new_session AS (
    SELECT gen_random_uuid() AS id
)
INSERT INTO auth_sessions (
    id,
    family_id,
    user_id,
    token_hash,
    expires_at,
    user_agent,
    ip_address
)
SELECT
    id,
    id,
    $1::text::uuid,
    $2,
    $3,
    $4,
    $5
FROM new_session
RETURNING id::text AS id, family_id::text AS family_id
`

type CreateAuthSessionParams struct {
	UserID    string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UserAgent string
	IpAddress string
}

type CreateAuthSessionRow struct {
	ID       string
	FamilyID string
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (CreateAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i CreateAuthSessionRow
	err := row.Scan(&i.ID, &i.FamilyID)
	return i, err
}

const createRotatedAuthSession = `-- name: CreateRotatedAuthSession :one
INSERT INTO auth_sessions (
    family_id,
    user_id,
    parent_id,
    token_hash,
    expires_at,
    user_agent,
    ip_address
)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3::text::uuid,
    $4,
    $5,
    $6,
    $7
)
RETURNING id::text AS id
`

type CreateRotatedAuthSessionParams struct {
	FamilyID  string
	UserID    string
	ParentID  string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UserAgent string
	IpAddress string
}

func (q *Queries) CreateRotatedAuthSession(ctx context.Context, arg CreateRotatedAuthSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, createRotatedAuthSession,
		arg.FamilyID,
		arg.UserID,
		arg.ParentID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getAuthSessionByTokenHashForUpdate = `-- name: GetAuthSessionByTokenHashForUpdate :one
SELECT
    session.id::text AS id,
    session.family_id::text AS family_id,
    session.user_id::text AS user_id,
    app_user.username,
    session.consumed_at,
    session.grace_expires_at,
    session.grace_reuse_count,
    session.expires_at,
    session.revoked_at
FROM auth_sessions AS session
JOIN users AS app_user ON app_user.id = session.user_id
WHERE session.token_hash = $1
FOR UPDATE OF session
`

type GetAuthSessionByTokenHashForUpdateRow struct {
	ID              string
	FamilyID        string
	UserID          string
	Username        string
	ConsumedAt      pgtype.Timestamptz
	GraceExpiresAt  pgtype.Timestamptz
	GraceReuseCount int16
	ExpiresAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
}

func (q *Queries) GetAuthSessionByTokenHashForUpdate(ctx context.Context, tokenHash []byte) (GetAuthSessionByTokenHashForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByTokenHashForUpdate, tokenHash)
	var i GetAuthSessionByTokenHashForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.UserID,
		&i.Username,
		&i.ConsumedAt,
		&i.GraceExpiresAt,
		&i.GraceReuseCount,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAuthSessionFamilyByTokenHash = `-- name: GetAuthSessionFamilyByTokenHash :one
SELECT family_id::text AS family_id
FROM auth_sessions
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetAuthSessionFamilyByTokenHash(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, getAuthSessionFamilyByTokenHash, tokenHash)
	var family_id string
	err := row.Scan(&family_id)
	return family_id, err
}

const revokeAuthSessionFamily = `-- name: RevokeAuthSessionFamily :exec
UPDATE auth_sessions AS target
SET revoked_at = COALESCE(target.revoked_at, $1)
WHERE target.family_id = $2::text::uuid
`

type RevokeAuthSessionFamilyParams struct {
	RevokedTime pgtype.Timestamptz
	FamilyID    string
}

func (q *Queries) RevokeAuthSessionFamily(ctx context.Context, arg RevokeAuthSessionFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeAuthSessionFamily, arg.RevokedTime, arg.FamilyID)
	return err
}

const revokeAuthSessionFamilyByTokenHash = `-- name: RevokeAuthSessionFamilyByTokenHash :exec
UPDATE auth_sessions AS target
SET revoked_at = COALESCE(target.revoked_at, $1)
WHERE target.family_id = (
    SELECT source.family_id
    FROM auth_sessions AS source
    WHERE source.token_hash = $2
)
`

type RevokeAuthSessionFamilyByTokenHashParams struct {
	RevokedTime        pgtype.Timestamptz
	PresentedTokenHash []byte
}

func (q *Queries) RevokeAuthSessionFamilyByTokenHash(ctx context.Context, arg RevokeAuthSessionFamilyByTokenHashParams) error {
	_, err := q.db.Exec(ctx, revokeAuthSessionFamilyByTokenHash, arg.RevokedTime, arg.PresentedTokenHash)
	return err
}

const revokeUserAuthSessions = `-- name: RevokeUserAuthSessions :exec
UPDATE auth_sessions AS target
SET revoked_at = COALESCE(target.revoked_at, $1)
WHERE target.user_id = $2::text::uuid
`

type RevokeUserAuthSessionsParams struct {
	RevokedTime pgtype.Timestamptz
	UserID      string
}

func (q *Queries) RevokeUserAuthSessions(ctx context.Context, arg RevokeUserAuthSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeUserAuthSessions, arg.RevokedTime, arg.UserID)
	return err
}
