// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID              pgtype.UUID
	FamilyID        pgtype.UUID
	UserID          pgtype.UUID
	ParentID        pgtype.UUID
	TokenHash       []byte
	ConsumedAt      pgtype.Timestamptz
	GraceExpiresAt  pgtype.Timestamptz
	GraceReuseCount int16
	ExpiresAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	UserAgent       string
	IpAddress       string
	CreatedAt       pgtype.Timestamptz
}

type Collaboration struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	UserID    pgtype.UUID
	JoinedAt  pgtype.Timestamptz
}

type Project struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Title       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProjectFile struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	FileType    string
	Filename    string
	ObjectKey   string
	ContentType pgtype.Text
	UploadedBy  pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamptz
}

type Snapshot struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	State     []byte
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      pgtype.Timestamptz
}

type Workspace struct {
	ID        pgtype.UUID
	Name      string
	OwnerID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type WorkspaceInvitation struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Email       string
	Role        string
	Token       string
	InvitedBy   pgtype.UUID
	Status      string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	AcceptedAt  pgtype.Timestamptz
}

type WorkspaceMember struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	CreatedAt   pgtype.Timestamptz
}
