// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserTokenPurpose string

const (
	UserTokenPurposeVerifyEmail   UserTokenPurpose = "verify_email"
	UserTokenPurposeResetPassword UserTokenPurpose = "reset_password"
)

func (e *UserTokenPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserTokenPurpose(s)
	case string:
		*e = UserTokenPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for UserTokenPurpose: %T", src)
	}
	return nil
}

type NullUserTokenPurpose struct {
	UserTokenPurpose UserTokenPurpose
	Valid            bool // Valid is true if UserTokenPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserTokenPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.UserTokenPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserTokenPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserTokenPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserTokenPurpose), nil
}

type AuthSession struct {
	ID              pgtype.UUID
	FamilyID        pgtype.UUID
	UserID          pgtype.UUID
	ParentID        pgtype.UUID
	TokenHash       []byte
	ConsumedAt      pgtype.Timestamptz
	GraceExpiresAt  pgtype.Timestamptz
	GraceReuseCount int16
	ExpiresAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	UserAgent       string
	IpAddress       string
	CreatedAt       pgtype.Timestamptz
}

type Collaboration struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	UserID    pgtype.UUID
	JoinedAt  pgtype.Timestamptz
}

type Project struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Title       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProjectFile struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	FileType    string
	Filename    string
	ObjectKey   string
	ContentType pgtype.Text
	UploadedBy  pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamptz
}

type Snapshot struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	State     []byte
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Username        string
	Email           string
	HashedPassword  string
	CreatedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
}

type UserToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Purpose   UserTokenPurpose
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Workspace struct {
	ID        pgtype.UUID
	Name      string
	OwnerID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type WorkspaceInvitation struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Email       string
	Role        string
	Token       string
	InvitedBy   pgtype.UUID
	Status      string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	AcceptedAt  pgtype.Timestamptz
}

type WorkspaceMember struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	CreatedAt   pgtype.Timestamptz
}
