// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_access.sql

package db

import (
	"context"
)

const userCanAccessProject = `-- name: UserCanAccessProject :one
SELECT EXISTS (
    SELECT 1
    FROM workspace_members AS member
    JOIN projects AS project ON project.workspace_id = member.workspace_id
    WHERE project.id = $1::text::uuid
      AND member.user_id = $2::text::uuid
)
`

type UserCanAccessProjectParams struct {
	ProjectID string
	UserID    string
}

func (q *Queries) UserCanAccessProject(ctx context.Context, arg UserCanAccessProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, userCanAccessProject, arg.ProjectID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
