// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	ClaimAuthSessionGraceReuse(ctx context.Context, arg ClaimAuthSessionGraceReuseParams) (int64, error)
	ConsumeAuthSession(ctx context.Context, arg ConsumeAuthSessionParams) (int64, error)
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (CreateAuthSessionRow, error)
	CreateRotatedAuthSession(ctx context.Context, arg CreateRotatedAuthSessionParams) (string, error)
	GetAuthSessionByTokenHashForUpdate(ctx context.Context, tokenHash []byte) (GetAuthSessionByTokenHashForUpdateRow, error)
	GetAuthSessionFamilyByTokenHash(ctx context.Context, tokenHash []byte) (string, error)
	RevokeAuthSessionFamily(ctx context.Context, arg RevokeAuthSessionFamilyParams) error
	RevokeAuthSessionFamilyByTokenHash(ctx context.Context, arg RevokeAuthSessionFamilyByTokenHashParams) error
	RevokeUserAuthSessions(ctx context.Context, arg RevokeUserAuthSessionsParams) error
	UserCanAccessProject(ctx context.Context, arg UserCanAccessProjectParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
