// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	UserCanAccessProject(ctx context.Context, arg UserCanAccessProjectParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
