// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    username,
    hashed_password
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id::text AS id
`

type CreateUserParams struct {
	Email          string
	Username       string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (string, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username, arg.HashedPassword)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createUserToken = `-- name: CreateUserToken :exec
INSERT INTO user_tokens (
    user_id,
    purpose,
    token_hash,
    expires_at
)
VALUES (
    $1::text::uuid,
    $2::user_token_purpose,
    $3,
    $4
)
`

type CreateUserTokenParams struct {
	UserID    string
	Purpose   UserTokenPurpose
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateUserToken(ctx context.Context, arg CreateUserTokenParams) error {
	_, err := q.db.Exec(ctx, createUserToken,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id::text AS id
FROM users
WHERE email = $1
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, getUserIDByEmail, email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getUserTokenForUpdate = `-- name: GetUserTokenForUpdate :one
SELECT
    token.id::text AS id,
    token.user_id::text AS user_id,
    token.expires_at,
    token.used_at,
    app_user.email::text AS email
FROM user_tokens AS token
JOIN users AS app_user ON app_user.id = token.user_id
WHERE token.token_hash = $1
  AND token.purpose = $2::user_token_purpose
FOR UPDATE OF token
`

type GetUserTokenForUpdateParams struct {
	TokenHash []byte
	Purpose   UserTokenPurpose
}

type GetUserTokenForUpdateRow struct {
	ID        string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	Email     string
}

func (q *Queries) GetUserTokenForUpdate(ctx context.Context, arg GetUserTokenForUpdateParams) (GetUserTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserTokenForUpdate, arg.TokenHash, arg.Purpose)
	var i GetUserTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Email,
	)
	return i, err
}

const invalidateUserTokens = `-- name: InvalidateUserTokens :exec
UPDATE user_tokens
SET used_at = $1
WHERE user_id = $2::text::uuid
  AND purpose = $3::user_token_purpose
  AND used_at IS NULL
`

type InvalidateUserTokensParams struct {
	UsedAt  pgtype.Timestamptz
	UserID  string
	Purpose UserTokenPurpose
}

func (q *Queries) InvalidateUserTokens(ctx context.Context, arg InvalidateUserTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateUserTokens, arg.UsedAt, arg.UserID, arg.Purpose)
	return err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE users
SET email_verified_at = COALESCE(email_verified_at, $1)
WHERE id = $2::text::uuid
`

type MarkUserEmailVerifiedParams struct {
	VerifiedAt pgtype.Timestamptz
	UserID     string
}

func (q *Queries) MarkUserEmailVerified(ctx context.Context, arg MarkUserEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, markUserEmailVerified, arg.VerifiedAt, arg.UserID)
	return err
}

const markUserTokenUsed = `-- name: MarkUserTokenUsed :exec
UPDATE user_tokens
SET used_at = $1
WHERE id = $2::text::uuid
`

type MarkUserTokenUsedParams struct {
	UsedAt pgtype.Timestamptz
	ID     string
}

func (q *Queries) MarkUserTokenUsed(ctx context.Context, arg MarkUserTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markUserTokenUsed, arg.UsedAt, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET hashed_password = $1
WHERE id = $2::text::uuid
`

type UpdateUserPasswordParams struct {
	HashedPassword string
	UserID         string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.HashedPassword, arg.UserID)
	return err
}
